version: '3.8'

services:
  flask_server:
    build: .
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus/alert_rules.yaml:/etc/prometheus/alert_rules.yaml
    ports:
      - "9090:9090"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
